sudo: false
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy3-2.4.0"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]] && [[ $TRAVIS_PYTHON_VERSION != "pypy3-2.4.0" ]]; then pip install --upgrade pip setuptools; fi
install:
  - pip install "pkginfo<1.3"
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install twine
script: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coverage run --source=s3 setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: uD8PHILeMTgLA5c41d0mSB95jxPuANCZgFrTwtEjepbnzV5WqUw1+hlaKZdvMaja4Rsf5UWxNHC//3Z5sd5oh8i53xLUDwZmWki90Vl3dwxxD+jSjSDdM1m2Z2MoAFywSGTAs6MA5GVLFP/DqGQq1rIPz1hIUvDRsjI0rEnHH7pck6YtCXIAbb8+cYmt1V7DNNUoBFLXyd0rBCZvOUraedC/G7MI55ZS0DOgepqqaf9UbHjlM6vMTUL71Yx8Zl474kpKz2TzKvMX15BtdfLiVpRK8QEmvmUtuuHaRDPAkVWGc2TJigeIDHN3GoR4+p1SYY9y2MTYn6ReIrp/DAhnf66nhpSmIM0Jc5FSkaAeaImwvpc8OzKdAzDzbZiDHTxaF5Gnobo9N4TFBIFtwMSopmZJHwrRY378czJjDRJjvAs7Ejvqxqu4bqfpsU6xMMWlvdNWiKuAwwL1LzgdNH/pHKApSyp3eoyuc/zYes2H5z6kfWpFCaQWtrb0P9oUASddmN0Jl/dDgzNXSv036cHlAH7FJYwakYgU5wOAopK5cGkPsa9wHxba3neG9BJY8oYjcUCcAnwySQ9L+GjGH7iNWW6Jfh1UXaVOKN2ceVQuR8m9AUmm/M7xeZrH7CNxFh5kYAdh3sTORM7cUOkR0r22Oi6Arob3kcghk9TkH6cRIMc=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
